IDX_STOCKS = {
    # ── BANKING (20) ──────────────────────────────────────────────
    "BBCA.JK": "Bank Central Asia",
    "BBRI.JK": "Bank Rakyat Indonesia",
    "BMRI.JK": "Bank Mandiri",
    "BBNI.JK": "Bank Negara Indonesia",
    "BBTN.JK": "Bank Tabungan Negara",
    "BNGA.JK": "Bank CIMB Niaga",
    "BDMN.JK": "Bank Danamon Indonesia",
    "NISP.JK": "Bank OCBC NISP",
    "PNBN.JK": "Bank Pan Indonesia",
    "BJBR.JK": "Bank Pembangunan Daerah Jawa Barat",
    "BJTM.JK": "Bank Pembangunan Daerah Jawa Timur",
    "MEGA.JK": "Bank Mega",
    "BTPS.JK": "Bank BTPN Syariah",
    "BNII.JK": "Bank Maybank Indonesia",
    "AGRO.JK": "Bank Rakyat Indonesia Agroniaga",
    "BMAS.JK": "Bank Maspion Indonesia",
    "BACA.JK": "Bank Capital Indonesia",
    "BBHI.JK": "Allo Bank Indonesia",
    "ARTO.JK": "Bank Jago",
    "BBYB.JK": "Bank Neo Commerce",
    # ── TELCO & TOWER (8) ─────────────────────────────────────────
    "TLKM.JK": "Telkom Indonesia",
    "ISAT.JK": "Indosat Ooredoo Hutchison",
    "EXCL.JK": "XL Axiata",
    "FREN.JK": "Smartfren Telecom",
    "LINK.JK": "Link Net",
    "TBIG.JK": "Tower Bersama Infrastructure",
    "TOWR.JK": "Sarana Menara Nusantara",
    "MTEL.JK": "Dayamitra Telekomunikasi",
    # ── CONSUMER STAPLES (18) ─────────────────────────────────────
    "UNVR.JK": "Unilever Indonesia",
    "ICBP.JK": "Indofood CBP Sukses Makmur",
    "INDF.JK": "Indofood Sukses Makmur",
    "MYOR.JK": "Mayora Indah",
    "ROTI.JK": "Nippon Indosari Corpindo",
    "ULTJ.JK": "Ultra Jaya Milk Industry",
    "SIDO.JK": "Industri Jamu Sido Muncul",
    "CPIN.JK": "Charoen Pokphand Indonesia",
    "JPFA.JK": "Japfa Comfeed Indonesia",
    "MAIN.JK": "Malindo Feedmill",
    "CMRY.JK": "Cisarua Mountain Dairy",
    "GGRM.JK": "Gudang Garam",
    "HMSP.JK": "HM Sampoerna",
    "WIIM.JK": "Wismilak Inti Makmur",
    "CAMP.JK": "Campina Ice Cream Industry",
    "GOOD.JK": "Garudafood Putra Putri Jaya",
    "FOOD.JK": "Sentra Food Indonesia",
    "BOBA.JK": "Formosa Ingredient Factory",
    # ── HEALTHCARE & PHARMA (12) ──────────────────────────────────
    "KLBF.JK": "Kalbe Farma",
    "KAEF.JK": "Kimia Farma",
    "MERK.JK": "Merck Indonesia",
    "DVLA.JK": "Darya-Varia Laboratoria",
    "TSPC.JK": "Tempo Scan Pacific",
    "PYFA.JK": "Pyridam Farma",
    "HEAL.JK": "Medikaloka Hermina",
    "MIKA.JK": "Mitra Keluarga Karyasehat",
    "SILO.JK": "Siloam International Hospitals",
    "PRDA.JK": "Prodia Widyahusada",
    "SOHO.JK": "Soho Global Health",
    "INAF.JK": "Indofarma",
    # ── MINING & COAL (15) ────────────────────────────────────────
    "ADRO.JK": "Adaro Energy Indonesia",
    "PTBA.JK": "Bukit Asam",
    "ITMG.JK": "Indo Tambangraya Megah",
    "HRUM.JK": "Harum Energy",
    "DOID.JK": "Delta Dunia Makmur",
    "GEMS.JK": "Golden Energy Mines",
    "PTRO.JK": "Petrosea",
    "KKGI.JK": "Resource Alam Indonesia",
    "MBAP.JK": "Mitrabara Adiperdana",
    "MYOH.JK": "Samindo Resources",
    "PKPK.JK": "Perdana Karya Perkasa",
    "GTBO.JK": "Garda Tujuh Buana",
    "SMMT.JK": "Golden Eagle Energy",
    "FIRE.JK": "Alfa Energi Investama",
    "APEX.JK": "Apexindo Pratama Duta",
    # ── METALS & MINERALS (10) ────────────────────────────────────
    "MDKA.JK": "Merdeka Copper Gold",
    "ANTM.JK": "Aneka Tambang",
    "INCO.JK": "Vale Indonesia",
    "AMMN.JK": "Amman Mineral Internasional",
    "NCKL.JK": "Trimegah Bangun Persada",
    "MBMA.JK": "Merdeka Battery Materials",
    "DKFT.JK": "Central Omega Resources",
    "CITA.JK": "Cita Mineral Investindo",
    "IFSH.JK": "Ifishdeco",
    "TINS.JK": "Timah",
    # ── OIL, GAS & ENERGY (10) ────────────────────────────────────
    "PGAS.JK": "Perusahaan Gas Negara",
    "MEDC.JK": "Medco Energi Internasional",
    "ELSA.JK": "Elnusa",
    "RUIS.JK": "Radiant Utama Interinsco",
    "ENRG.JK": "Energi Mega Persada",
    "ESSA.JK": "Surya Esa Perkasa",
    "BIPI.JK": "Astrindo Nusantara Infrastruktur",
    "PGEO.JK": "Pertamina Geothermal Energy",
    "RAJA.JK": "Rukun Raharja",
    "BREN.JK": "Barito Renewables Energy",
    # ── PLANTATION (12) ───────────────────────────────────────────
    "AALI.JK": "Astra Agro Lestari",
    "LSIP.JK": "PP London Sumatra Indonesia",
    "SIMP.JK": "Salim Ivomas Pratama",
    "SSMS.JK": "Sawit Sumbermas Sarana",
    "DSNG.JK": "Dharma Satya Nusantara",
    "TAPG.JK": "TBS Energi Utama",
    "PALM.JK": "Provident Agro",
    "SGRO.JK": "Sampoerna Agro",
    "TBLA.JK": "Tunas Baru Lampung",
    "BWPT.JK": "Eagle High Plantations",
    "JAWA.JK": "Jaya Agra Wattie",
    "ANJT.JK": "Austindo Nusantara Jaya",
    # ── PROPERTY (18) ─────────────────────────────────────────────
    "BSDE.JK": "Bumi Serpong Damai",
    "CTRA.JK": "Ciputra Development",
    "PWON.JK": "Pakuwon Jati",
    "SMRA.JK": "Summarecon Agung",
    "MKPI.JK": "Metropolitan Kentjana",
    "DMAS.JK": "Puradelta Lestari",
    "MTLA.JK": "Metropolitan Land",
    "APLN.JK": "Agung Podomoro Land",
    "LPKR.JK": "Lippo Karawaci",
    "KIJA.JK": "Kawasan Industri Jababeka",
    "DILD.JK": "Intiland Development",
    "GPRA.JK": "Perdana Gapuraprima",
    "PLIN.JK": "Plaza Indonesia Realty",
    "URBN.JK": "Urban Jakarta Propertindo",
    "EMDE.JK": "Megapolitan Developments",
    "BCIP.JK": "Bumi Citra Permai",
    "POLL.JK": "Pollux Properti Indonesia",
    "TARA.JK": "Sitara Propertindo",
    # ── CONSTRUCTION & INFRASTRUCTURE (12) ───────────────────────
    "JSMR.JK": "Jasa Marga",
    "WIKA.JK": "Wijaya Karya",
    "PTPP.JK": "PP Persero",
    "ADHI.JK": "Adhi Karya",
    "WTON.JK": "Wijaya Karya Beton",
    "NRCA.JK": "Nusa Raya Cipta",
    "ACST.JK": "Acset Indonusa",
    "WSBP.JK": "Waskita Beton Precast",
    "IDPR.JK": "Indonesia Pondasi Raya",
    "PBSA.JK": "Paramita Bangun Sarana",
    "BTON.JK": "Betonjaya Manunggal",
    "DGIK.JK": "Nusa Konstruksi Enjiniring",
    # ── RETAIL & CONSUMER DISCRETIONARY (14) ─────────────────────
    "MAPI.JK": "Mitra Adiperkasa",
    "ACES.JK": "Ace Hardware Indonesia",
    "AMRT.JK": "Sumber Alfaria Trijaya",
    "LPPF.JK": "Matahari Department Store",
    "RALS.JK": "Ramayana Lestari Sentosa",
    "MIDI.JK": "Midi Utama Indonesia",
    "ERAA.JK": "Erajaya Swasembada",
    "CSAP.JK": "Catur Sentosa Adiprana",
    "MPPA.JK": "Matahari Putra Prima",
    "HERO.JK": "Hero Supermarket",
    "KOIN.JK": "Kokoh Inti Arebama",
    "SONA.JK": "Sona Topas Tourism Industry",
    "RANC.JK": "Supra Boga Lestari",
    "TKMP.JK": "Tigaraksa Satria",
    # ── AUTOMOTIVE & HEAVY EQUIPMENT (8) ─────────────────────────
    "ASII.JK": "Astra International",
    "AUTO.JK": "Astra Otoparts",
    "GJTL.JK": "Gajah Tunggal",
    "SMSM.JK": "Selamat Sempurna",
    "IMAS.JK": "Indomobil Sukses Internasional",
    "INDS.JK": "Indospring",
    "MASA.JK": "Multistrada Arah Sarana",
    "BRAM.JK": "Indo Kordsa",
    # ── CEMENT & BUILDING MATERIALS (8) ──────────────────────────
    "SMGR.JK": "Semen Indonesia",
    "INTP.JK": "Indocement Tunggal Prakarsa",
    "SMBR.JK": "Semen Baturaja",
    "WCID.JK": "Wahana Cahaya Indonesia",
    "ARNA.JK": "Arwana Citramulia",
    "TOTO.JK": "Surya Toto Indonesia",
    "MARK.JK": "Mark Dynamics Indonesia",
    "CRBK.JK": "Cipta Rasa Budimakmur Kencana",
    # ── CHEMICALS & PLASTICS (8) ──────────────────────────────────
    "TPIA.JK": "Chandra Asri Pacific",
    "BRPT.JK": "Barito Pacific",
    "BUDI.JK": "Budi Starch and Sweetener",
    "EKAD.JK": "Ekadharma International",
    "SRSN.JK": "Indo Acidatama",
    "INCI.JK": "Intanwijaya Internasional",
    "DPNS.JK": "Duta Pertiwi Nusantara",
    "AGII.JK": "Aneka Gas Industri",
    # ── STEEL, CABLES & METALS MANUFACTURING (10) ────────────────
    "ISSP.JK": "Steel Technologies Indonesia",
    "LION.JK": "Lion Metal Works",
    "LMSH.JK": "Lionmesh Prima",
    "KBLI.JK": "KMI Wire and Cable",
    "SCCO.JK": "Supreme Cable Manufacturing",
    "VOKS.JK": "Voksel Electric",
    "JECC.JK": "Jembo Cable Company",
    "ALKA.JK": "Alakasa Industrindo",
    "PTSN.JK": "Sat Nusapersada",
    "NIKL.JK": "Pelat Timah Nusantara",
    # ── MEDIA & TECHNOLOGY (10) ───────────────────────────────────
    "MNCN.JK": "Media Nusantara Citra",
    "SCMA.JK": "Surya Citra Media",
    "EMTK.JK": "Elang Mahkota Teknologi",
    "NETV.JK": "Net Visi Media",
    "MSIN.JK": "MNC Studios International",
    "KOPI.JK": "Fanindo Cipta Propertindo",
    "DMMX.JK": "Digital Mediatama Maxima",
    "MCAS.JK": "M Cash Integrasi",
    "EDGE.JK": "Indointernet",
    "MTDL.JK": "Metrodata Electronics",
    # ── FINTECH & MULTIFINANCE (8) ────────────────────────────────
    "BFIN.JK": "BFI Finance Indonesia",
    "ADMF.JK": "Adira Dinamika Multi Finance",
    "CFIN.JK": "Clipan Finance Indonesia",
    "HDFA.JK": "Radana Bhaskara Finance",
    "BBLD.JK": "Buana Finance",
    "MFIN.JK": "Mandala Multifinance",
    "PNLF.JK": "Panin Financial",
    "WOMF.JK": "Wahana Ottomitra Multiartha",
    # ── LOGISTICS & TRANSPORTATION (12) ──────────────────────────
    "BIRD.JK": "Blue Bird",
    "ASSA.JK": "Adi Sarana Armada",
    "SMDR.JK": "Samudera Indonesia",
    "HITS.JK": "Humpuss Intermoda Transportasi",
    "TMAS.JK": "Temas",
    "MBSS.JK": "Mitrabahtera Segara Sejati",
    "RIGS.JK": "Rig Tenders Indonesia",
    "WEHA.JK": "Weha Transportasi Indonesia",
    "TAXI.JK": "Express Transindo Utama",
    "SAFE.JK": "Steady Safe",
    "IPCM.JK": "Jasa Armada Indonesia",
    "CMPP.JK": "Air Asia Indonesia",
    # ── INSURANCE (8) ─────────────────────────────────────────────
    "ABDA.JK": "Asuransi Bina Dana Arta",
    "ASDM.JK": "Asuransi Dayin Mitra",
    "ASRM.JK": "Asuransi Ramayana",
    "MREI.JK": "Maskapai Reasuransi Indonesia",
    "PNIN.JK": "Panin Insurance",
    "LPGI.JK": "Lippo General Insurance",
    "AHAP.JK": "Asuransi Harta Aman Pratama",
    "LIFE.JK": "Asuransi Jiwa Syariah Jasa Mitra Abadi",
    # ── HOLDING & DIVERSIFIED (8) ─────────────────────────────────
    "SRTG.JK": "Saratoga Investama Sedaya",
    "MLPL.JK": "Multipolar",
    "BHIT.JK": "MNC Investama",
    "DNET.JK": "Indoritel Makmur Internasional",
    "PNSE.JK": "Pudjiadi and Sons",
    "MYRX.JK": "Hanson International",
    "IKAI.JK": "Intikeramik Alamasri Industri",
    "KPIG.JK": "MNC Land",
    # ── TEXTILES & APPAREL (6) ────────────────────────────────────
    "RICY.JK": "Ricky Putra Globalindo",
    "SSTM.JK": "Sunson Textile Manufacturer",
    "POLU.JK": "Golden Flower",
    "UNIT.JK": "Nusantara Inti Corpora",
    "TFCO.JK": "Tifico Fiber Indonesia",
    "CNTX.JK": "Century Textile Industry",
    # ── FOOD & BEVERAGE MANUFACTURING (8) ────────────────────────
    "MLBI.JK": "Multi Bintang Indonesia",
    "DLTA.JK": "Delta Djakarta",
    "SKBM.JK": "Sekar Bumi",
    "SKLT.JK": "Sekar Laut",
    "CLEO.JK": "Sariguna Primatirta",
    "KEJU.JK": "Mulia Boga Raya",
    "PMMP.JK": "Panca Mitra Multiperdana",
    "PCAR.JK": "Prima Cakrawala Abadi",
    # ── TIMBER, PAPER & PACKAGING (5) ────────────────────────────
    "FASW.JK": "Fajar Surya Wisesa",
    "INKP.JK": "Indah Kiat Pulp and Paper",
    "TKIM.JK": "Pabrik Kertas Tjiwi Kimia",
    "SPMA.JK": "Suparma",
    "DAJK.JK": "Dwi Aneka Jaya Kemasindo",
    # ── GLASS, CERAMICS & MISC INDUSTRY (6) ──────────────────────
    "AMFG.JK": "Asahimas Flat Glass",
    "MLIA.JK": "Mulia Industrindo",
    "KIAS.JK": "Keramika Indonesia Assosiasi",
    "YPAS.JK": "Yanaprima Hastapersada",
    "AKPI.JK": "Argha Karya Prima Industry",
    "IGAR.JK": "Champion Pacific Indonesia",
}
